### ISSUE TITLE
能否加入查看其他设备ip的功能

### ISSUE THREAD

**Issue by Qiyue0726** [kaaass/ZerotierFix#71]
请问能否实现像tailscale一样，可以看到当前网络下其他设备的ip，而不用去官方的管理界面那里查看

**Comment by kaaass** [comment]
Zerotier 的设计不允许网络成员向控制器（比如官网管理界面）获取网络中的全部成员信息，所以 Zerotier Fix 没法实现这个功能。官方控制器倒是提供了 API 允许请求网络中的节点信息，但是这就需要实现登录相关的逻辑，而且第三方控制器也没法得到支持，感觉有点超出 Zerotier Fix 的职责范围。总体而言，目前因为技术上的限制所以暂时不考虑实现这个功能了。

The design of Zerotier does not allow network members to obtain complete member information from the controller (e.g., the official website management interface), so Zerotier Fix will not be able to implement this feature. The official controller does provide an API to request information about nodes in the network, but this requires implementing login-related logic, and third-party controllers cannot be supported either. It feels a bit beyond the scope of Zerotier Fix's responsibilities. Overall, due to technical limitations, this feature is not being considered for implementation at this time.
