### ISSUE TITLE
Option to only override DNS servers when in cellular data/whitelist WiFi?

### ISSUE THREAD

**Issue by parasiteoflife** [kaaass/ZerotierFix#72]
I'll try to explain the better I can my scenario.

In my country ISPs only give static public IPs to enterprise/business, and NAT'd IPs to residential users so in order for me to access any of my self-hosted services I have to rely on Zerotier.

Currently I'm hosting pi-hole and adguard, in order for me to always use them as my DNS I have to enable Zerotier DNS override options, this is great when I'm not at home or using cellular data, but it's not so great when I'm actually at home on my own WiFi because ZT will still route the DNS through the ZT's IPs when I can use my local network to access them. In order to avoid this is that I'm requesting this feature.

- Option to disable DNS override/custom DNS when we are connected on WiFi
- Option to whitelist WiFi SSIDs in which DNS override wont be used <---- this is the ideal because connected to WiFi != being in the local network

Thanks for reading.

**Comment by kaaass** [comment]
Thanks for your detailed description!

I still do not quite understand the problem you met. When you are at home and connect to your own WiFi, the ZT should be able to connect to your device through its local IP address without further configuration. Thus, connecting to your device whether through ZT's IP or local network IP should work almost the same.

BTW, since we plan to support some automation tools (e.g., Tasker #9), would this feature solve your problem? For example, you might want to create two ZT networks, one with DNS config and the other not. When you connect to a certain WiFi, you can configure the Tasker app to send an Intent to enable the network without DNS config.

**Comment by kaaass** [comment]
The issue will be closed since there's no further conversation for a while. Feel free to leave comments if this feature is still wanted.
